config/routes.rb
WepimApp::Application.routes.draw do

  if Conf.manager?
    root :to => 'welcome#index'
    resource :admin_session
    match 'admin_logout' => 'admin_sessions#destroy', :as => :admin_logout
    match 'admin/new' => 'admin#new'
    match 'admin/edit' => 'admin#edit'
    match 'admin/create' => 'admin#create'
    match 'admin' => 'admin#index'
    match 'welcome/login' => 'welcome#login'
    match 'welcome/scenario' => 'welcome#start_scenario'
    match "welcome/shutdown/:id" => "welcome#shutdown"
    match 'welcome/start/:id' => "welcome#start"
    match 'welcome/redirect/:id' => "welcome#redirect"
    match 'welcome/refresh' => 'welcome#refresh'
    match 'welcome/killall' => "welcome#killall"
    match 'welcome' => 'welcome#index'
    match 'waiting/:id' => 'welcome#waiting', :as => :waiting
    match 'waiting/confirm/:id' => 'welcome#confirm_server_ready', :as => :confirm_server_ready
    match '/*else' => 'welcome#index'
  else
    root :to => 'users#index'
    match 'index' => 'users#index'
    match 'program' => 'program#index', :as => :program
    match 'engine' => 'engine#index', :as => :engine
    match 'wepic' => 'wepic#index', :as => :wepic
    match 'query' => 'query#index', :as => :query
    resources :pictures do
      member do
        get :images
      end
    end
    match 'query/create' => 'query#create'
    match 'query/insert' => 'query#insert'
    match 'query/relation' => 'query#relation'
    match 'query/username' => 'query#username'
    match 'query/described_rule/add' => 'query#add_described_rule'
    match 'query/described_rule/remove' => 'query#remove_described_rule'
    match 'wepic/online' => 'wepic#online'
    match 'program/delegations/get' => 'program#delegations'
    match 'program/delegations/accept' => 'program#accept'
    match 'program/delegations/reject' => 'program#reject'
    match 'program/get' => 'program#get'
    match 'contacts/:username/pictures' => 'pictures#contact'
    match 'wepic/update' => 'wepic#update'
    match 'pictures/update' => 'pictures#update'
    match 'wepic/comments/latest' => 'wepic#getLatestComments'
    match 'wepic/comments/add' => 'wepic#addComment'
    match 'wepic/comments/remove' => 'wepic#removeComment'
    match 'wepic/send_picture' => 'wepic#send_picture'
  end
  resources :users, :user_sessions
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'list' => 'users#list'
  match 'admin' => 'admin#index', :as => :admin

end

app/models/admin_session.rb
class AdminSession < Authlogic::Session::Base
end

app/controllers/admin_sessions_controller.rb
class AdminSessionsController < ApplicationController
  # before_filter :require_no_user, :only => [:new, :create]
  # before_filter :require_user, :only => :destroy
  
  def index
    @admin_session = AdminSession.new
  end
  
  def new
    @admin_session = AdminSession.new
    puts @admin_session
  end
  
  def create
    @admin_session = AdminSession.new(params[:admin_session])
    if @admin_session.save
      flash[:notice] = "Login successful!"
      redirect_to '/'
    else
      render :action => :new
    end
  end
  
  def destroy
    current_admin_session.destroy
    flash[:notice] = "Logout successful!"
    redirect_to '/'
  end
end

app/views/admin_sessions/new.html.erb
<div class="opacity"></div>
<div class="content">
<% if @admin_session %>
<h2>Admin Login</h2>
<%= form_for @admin_session, :url => admin_session_path do |f| %>
  <% if @admin_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_session.errors.count, "error") %> prohibited this admin_session from being saved:</h2>

      <ul>
      <% @admin_session.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :login %><br />
  <%= f.text_field :login %><br />
  <br />
  <%= f.label :password %><br />
  <%= f.password_field :password %><br />
  <br />
  <%= f.check_box :remember_me %><%= f.label :remember_me %><br />
  <br />
  <%= f.submit "Login" %>
<% end %>
<% end %>
</div>